version: 2
jobs:
  build:
    docker:
      - image: poldrack/statsthinking21
    steps:
      - add_ssh_keys:
          fingerprints:
            - "16:24:d9:0f:6b:81:7f:47:d4:48:14:86:3d:2d:2a:ba"
      - checkout
      - run:
           name: rendering pdf
           command: |
             make render-pdf
           no_output_timeout: 1200
      - run:
           name: rendering epub
           command: |
             make render-epub
           no_output_timeout: 1200
      - run:
           name: rendering gitbook
           command: |
             make render-gitbook
           no_output_timeout: 1200
      - run:
           name: check out site repo
           command: |
             cd /tmp
             ssh-keyscan github.com >> ~/.ssh/known_hosts
             git clone git@github.com:psych10/thinkstats-R.git 
             cd thinkstats-R
             cp -r ~/project/_book/* . 
             git add .
             git config --global user.email poldrack@gmail.com
             git config --global user.name "Russ Poldrack"
             git commit -m"automated update"
             git push origin master

